defaults {
        user_friendly_names yes
        find_multipaths yes
        polling_interval 10
        max_fds max
}

devices {
        device {
                # Information may change depending on disk array
                vendor "COMPELNT"
                product "Compellent Vol"
                path_grouping_policy group_by_prio
                path_selector "service-time 0"
                path_checker tur
                hardware_handler "1 alua"
                prio alua
                failback immediate
                rr_weight priorities
                no_path_retry 24
                rr_min_io_rq 1
        }
}
blacklist {
        # Exemple blacklist node
        devnode "^sda"
}